# Site Settings
title: CS 419 Production Computer Graphics
email: shaffer1@illinois.edu
description: >
  Webpage for the course CS 419 at the University of Illinois
baseurl: "" 
url: "http://UIllinoisGraphics.github.io"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
